name: CI
on: [master]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JRE 8 as libs for R8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Set up JDK 14 for build
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build & test the agent standalone
        run: ./gradlew quickTest

      - name: Build & test the full distributable
        run: ./gradlew distTest

      - uses: actions/upload-artifact@v2
        with:
          name: distributables
          path: build/libs/*-dist.jar
          if-no-files-found: error

      - name: Publish tagged release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*-dist.jar
          file_glob: true
          tag: ${{ github.ref }}